# Generated by Django 4.1.5 on 2023-06-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_chana"),
    ]

    operations = [
        migrations.CreateModel(
            name="petroluem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
            ],
        ),
    ]
