# Generated by Django 4.1.5 on 2023-06-13 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_petroluem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="chana",
        ),
    ]
