# Generated by Django 4.1.5 on 2023-06-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_delete_chana"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
    ]
