# Generated by Django 4.1.5 on 2023-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_popularperson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popularperson",
            name="date",
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "popular_persons",
                    models.ManyToManyField(
                        related_name="dates", to="pages.popularperson"
                    ),
                ),
            ],
        ),
    ]
