# Generated by Django 4.1.5 on 2023-06-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_remove_popularperson_date_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopPopularPersons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("person1_name", models.CharField(max_length=255)),
                ("person1_video_count", models.PositiveIntegerField()),
                ("person2_name", models.CharField(max_length=255)),
                ("person2_video_count", models.PositiveIntegerField()),
                ("person3_name", models.CharField(max_length=255)),
                ("person3_video_count", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Date",
        ),
        migrations.DeleteModel(
            name="PopularPerson",
        ),
    ]
