# Generated by Django 4.1.5 on 2023-06-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_toppopularpersons_delete_date_delete_popularperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toppopularpersons",
            name="person1_video_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="toppopularpersons",
            name="person2_video_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="toppopularpersons",
            name="person3_video_count",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
