# Generated by Django 4.1.5 on 2023-06-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_alter_toppopularpersons_person1_video_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newschannel",
            name="facebook_likes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
