# Generated by Django 4.1.5 on 2023-06-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_newschannel_facebook_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newschannel",
            name="facebook_likes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="newschannel",
            name="subscribers",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="newschannel",
            name="twitter_followers",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
