# Generated by Django 4.1.5 on 2023-06-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_newschannel_facebook_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newschannel",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
