# Generated by Django 4.1.5 on 2023-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newschannel",
            name="channel_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="credibility_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="facebook_page",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="fake_news_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="founded_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="headquarters",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="official_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="politcial_spectrum",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="subscribers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="twitter_followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="twitter_handle",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="youtube_channel",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newschannel",
            name="youtube_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
