# Generated by Django 4.1.5 on 2023-05-22 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_newschannel_channel_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newschannel",
            name="twitter_followers",
        ),
    ]
