# Generated by Django 4.1.5 on 2023-05-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_remove_newschannel_twitter_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="newschannel",
            name="twitter_followers",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
