# Generated by Django 4.1.5 on 2023-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_newschannel_twitter_followers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("rank", models.IntegerField()),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
    ]
