# Generated by Django 4.1.5 on 2023-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_trendingtopic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingtopic",
            name="rank",
            field=models.IntegerField(unique=True),
        ),
    ]
