# Generated by Django 4.1.5 on 2023-05-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_alter_trendingtopic_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="newschannel",
            name="channel_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("transcript", models.TextField()),
                ("published_date", models.DateTimeField()),
                ("video_url", models.URLField(max_length=2000)),
                ("thumbnail_url", models.URLField(max_length=2000)),
                ("topic", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="pages.newschannel",
                    ),
                ),
            ],
        ),
    ]
