# Generated by Django 4.1.5 on 2023-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_newschannel_channel_id_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingtopic",
            name="synopsis",
            field=models.TextField(blank=True),
        ),
    ]
