# Generated by Django 4.1.5 on 2023-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_alter_video_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="topic",
            field=models.CharField(max_length=255),
        ),
    ]
